// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "start_at", Type: field.TypeTime},
		{Name: "end_at", Type: field.TypeTime},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// TagEventsColumns holds the columns for the "tag_events" table.
	TagEventsColumns = []*schema.Column{
		{Name: "tag_id", Type: field.TypeInt},
		{Name: "event_id", Type: field.TypeInt},
	}
	// TagEventsTable holds the schema information for the "tag_events" table.
	TagEventsTable = &schema.Table{
		Name:       "tag_events",
		Columns:    TagEventsColumns,
		PrimaryKey: []*schema.Column{TagEventsColumns[0], TagEventsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tag_events_tag_id",
				Columns:    []*schema.Column{TagEventsColumns[0]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "tag_events_event_id",
				Columns:    []*schema.Column{TagEventsColumns[1]},
				RefColumns: []*schema.Column{EventsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EventsTable,
		TagsTable,
		TagEventsTable,
	}
)

func init() {
	TagEventsTable.ForeignKeys[0].RefTable = TagsTable
	TagEventsTable.ForeignKeys[1].RefTable = EventsTable
}
